name: Build IPA
on: workflow_dispatch # This allows you to run it manually with a button click

jobs:
  build:
    runs-on: macos-14 # Uses Apple Silicon runner (Sonoma)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # <--- Crucial for Amperfy to work!

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Archive
        run: |
          xcodebuild -scheme Amperfy \
          -destination "generic/platform=iOS" \
          -archivePath Amperfy.xcarchive \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          clean archive

      - name: Export IPA
        run: |
          mkdir Payload
          cp -r Amperfy.xcarchive/Products/Applications/Amperfy.app Payload/
          zip -r Amperfy.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Amperfy-Unsigned
          path: Amperfy.ipa
